Movement Definitions:
  - MovementDefinition:
      UniqueId: "movement_land"
      Name: "Land Movement"
      movementDomain: "surface"
      movementType: "land"
      movementUnit: "1 m"
      movementPeriod: "1 second"
      baseSpeedMultiplier: 1.0
      requiresFuel: false
      terrainMovementCosts:
        plains: 1.0
        forest: 1.5
        mountain: 3.0
        desert: 1.2
        water: 0.0
      terrainMovementMultipliers:
        plains: 1.0
        forest: 0.7
        mountain: 0.3
        desert: 0.8
        water: 0.1
      infrastructureBonuses:
        road: 2.0
        magrail: 3.0
      movementIcon: "Icon_LandMovement"
      movementColor: "#8B4513"

  - MovementDefinition:
      UniqueId: "movement_sea"
      Name: "Sea Movement"
      movementDomain: "surface"
      movementType: "sea"
      movementUnit: "1 m"
      movementPeriod: "1 second"
      baseSpeedMultiplier: 0.8
      requiresFuel: false
      terrainMovementCosts:
        plains: 0.5
        forest: 0.3
        mountain: 0.1
        desert: 0.4
        water: 1.0
      terrainMovementMultipliers:
        plains: 0.5
        forest: 0.3
        mountain: 0.1
        desert: 0.4
        water: 1.0
      infrastructureBonuses:
        road: 1.5
        magrail: 2.0
      movementIcon: "Icon_SeaMovement"
      movementColor: "#0000FF"

  - MovementDefinition:
      UniqueId: "movement_air"
      Name: "Air Movement"
      movementDomain: "surface"
      movementType: "air"
      movementUnit: "1 m"
      movementPeriod: "1 second"
      baseSpeedMultiplier: 1.5
      requiresFuel: true
      fuelConsumptionRate: 0.5
      movementIcon: "Icon_AirMovement"
      movementColor: "#87CEEB"

  - MovementDefinition:
      UniqueId: "movement_sublight"
      Name: "Sub-Light Movement"
      movementDomain: "space"
      movementType: "sublight"
      movementUnit: "1 AU"
      movementPeriod: "1 day"
      baseSpeedMultiplier: 0.5
      requiresFuel: true
      fuelConsumptionRate: 1.0
      gravitationalEffects:
        low: 1.3
        normal: 1.0
        high: 0.6
      movementRestrictions:
        - "Requires clear orbital path"
        - "Affected by gravitational wells"
      movementIcon: "Icon_SubLightMovement"
      movementColor: "#FFA500"

  - MovementDefinition:
      UniqueId: "movement_ftl"
      Name: "FTL Movement"
      movementDomain: "space"
      movementType: "ftl"
      movementUnit: "1 ly"
      movementPeriod: "1 day"
      baseSpeedMultiplier: 10.0
      requiresFuel: true
      fuelConsumptionRate: 2.0
      hyperlaneCompatibility:
        small: 0.3
        medium: 0.8
        large: 1.0
      movementRestrictions:
        - "Requires hyperlane network"
        - "Limited by ship size"
      movementBonuses:
        - "Extreme speed"
        - "Ignores most obstacles"
      movementIcon: "Icon_FTLMovement"
      movementColor: "#800080"
